blueprint:
  name: TRVZB Calibrator
  description: Calibrate your TRVZB using an external sensor
  domain: automation
  input:
    trv:
      name: Smart TRV
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    trv_calibration_number:
      name: TRV Calibration Entity
      description: Calibration
      selector:
        entity:
          domain: number
          device_class: temperature
    delay_in_minutes:
      name: Delay in minutes
      description: Your thermostat will take some time to update the current temperature after calibration. The delay should be higher than this time.
      default: 1
      selector:
        number:
          min: 1
          max: 60
          step: 1

mode: restart

variables:
  trv: !input trv
  trv_calibration_number: !input trv_calibration_number
  temperature_sensor: !input temperature_sensor                                

trigger:
  - platform: state
    entity_id: !input trv
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input trv_calibration_number
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input temperature_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0

condition:
  - condition: template
    value_template: '{{ state_attr(trv, "current_temperature") != None }}'
  - condition: template
    value_template: '{{ states(trv_calibration_number) != "unavailable" and states(trv_calibration_number) != "unknown" }}'
  - condition: template
    value_template: '{{ states(temperature_sensor) != "unavailable" and states(temperature_sensor) != "unknown" }}'

action:
  - delay:
      hours: 0
      minutes: !input delay_in_minutes
      seconds: 0
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: !input trv_calibration_number
    data:
      value: >- 
            {% set room_temperature = states(temperature_sensor) | float | round(1) %}
            {% set trv_temperature = state_attr(trv, "current_temperature") | float | round(1) %}
            {% set trv_calibration = states(trv_calibration_number) | float | round(1) %}

            {% set offset_temp = (room_temperature - trv_temperature + trv_calibration | float) | round(1) %}
            
            {% if room_temperature != trv_temperature -%}
                {{ offset_temp }}
            {%- endif %}